name: GitHub pypeline test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        pip install PyQt5
        pip install pyinstaller
    - name: Build EXE
      run: |
        pyinstaller pipeline_test.spec
    - name: Go to dist folder
      run: |
        cd dist
        dir
        tar.exe -a -c -f pipeline_test.zip pipeline_test.exe
        dir
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: dist/pipeline_test.zip
        retention-days: 5
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.head_commit.message }}
        release_name: Release A_${{ github.event.head_commit.message }}
        draft: false
        prerelease: false
    - name: upload windows artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/pipeline_test.zip
        asset_name: pipeline_test.zip
        asset_content_type: application/zip
