name: GitHub pypeline test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt5
        pip install pyinstaller
    - name: Build EXE
      run: |
        pyinstaller pypeline_test.spec
    - uses: actions/download-artifact@v3
      with:
        name: dist/pypeline_test.exe
